package main;

	import java.io.IOException;
	import java.io.*;
	import java.net.*;
import java.text.DecimalFormat;
import java.util.logging.Level;
	import java.util.logging.Logger;
	import javax.swing.JOptionPane;
	import javax.swing.table.DefaultTableModel;
	
	/**
	 *
	 * @author Bushmek
	 */
	
	public class Frame extends javax.swing.JFrame {
	    private static Socket socket;
	    private static ObjectOutputStream out;
	    private static ObjectInputStream in;
	    private static String user;
	    private static char[] pass;
	   
	    /**
	     * Creates new form Frame
	     */
	    public Frame() {
	        initComponents();
	        jTabbedPane1.setEnabledAt(1, false);
	        jTabbedPane1.setEnabledAt(2, false);
	        jTabbedPane1.setEnabledAt(3, false);
	        jTabbedPane1.setEnabledAt(4, false);
	        jTabbedPane1.setEnabledAt(5, false);
	        while(true){
	        try {
	            socket = new Socket("127.0.0.1", 12345);
	            break;
	            }catch(IOException e) {
	                int reply=JOptionPane.showConfirmDialog(null, "Немає доступу до серверу\nПовторити спробу?", "Помилка", JOptionPane.YES_NO_OPTION);
	                if(reply==JOptionPane.YES_OPTION){
	                    
	                }
	                else{
	                System.exit(0);
	                }
	        	e.printStackTrace();
	        }
	        }
	        try{
	            out=new ObjectOutputStream(socket.getOutputStream());
	            in = new ObjectInputStream(socket.getInputStream());
	        }catch(IOException e){
	            e.printStackTrace();
	        }
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {

	        jTabbedPane1 = new javax.swing.JTabbedPane();
	        jPanel1 = new javax.swing.JPanel();
	        jTextField1 = new javax.swing.JTextField();
	        jPasswordField1 = new javax.swing.JPasswordField();
	        jButton1 = new javax.swing.JButton();
	        jLabel1 = new javax.swing.JLabel();
	        jLabel2 = new javax.swing.JLabel();
	        jPanel2 = new javax.swing.JPanel();
	        jLabel3 = new javax.swing.JLabel();
	        jLabel4 = new javax.swing.JLabel();
	        jLabel5 = new javax.swing.JLabel();
	        insertYear = new javax.swing.JTextField();
	        insertProd = new javax.swing.JTextField();
	        jButton2 = new javax.swing.JButton();
	        insertCost = new javax.swing.JTextField();
	        jPanel3 = new javax.swing.JPanel();
	        jLabel9 = new javax.swing.JLabel();
	        delYear = new javax.swing.JTextField();
	        jButton4 = new javax.swing.JButton();
	        jPanel4 = new javax.swing.JPanel();
	        jLabel6 = new javax.swing.JLabel();
	        jLabel7 = new javax.swing.JLabel();
	        jLabel8 = new javax.swing.JLabel();
	        updYear = new javax.swing.JTextField();
	        updProd = new javax.swing.JTextField();
	        updCost = new javax.swing.JTextField();
	        jButton3 = new javax.swing.JButton();
	        jPanel5 = new javax.swing.JPanel();
	        jScrollPane1 = new javax.swing.JScrollPane();
	        jTable1 = new javax.swing.JTable();
	        jButton5 = new javax.swing.JButton();
	        jPanel6 = new javax.swing.JPanel();
	        jButton6 = new javax.swing.JButton();
	        jScrollPane2 = new javax.swing.JScrollPane();
	        jTable2 = new javax.swing.JTable();
	        jLabel10 = new javax.swing.JLabel();

	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

	        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

	        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
	        jButton1.setText("Вхід");
	        jButton1.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton1ActionPerformed(evt);
	            }
	        });

	        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
	        jLabel1.setText("Логін");

	        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
	        jLabel2.setText("Пароль");

	        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
	        jPanel1.setLayout(jPanel1Layout);
	        jPanel1Layout.setHorizontalGroup(
	            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
	                .addContainerGap(318, Short.MAX_VALUE)
	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
	                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addGap(11, 11, 11))
	                            .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
	                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
	                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(37, 37, 37))
	                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
	                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(30, 30, 30)))
	                .addGap(281, 281, 281))
	        );
	        jPanel1Layout.setVerticalGroup(
	            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel1Layout.createSequentialGroup()
	                .addGap(75, 75, 75)
	                .addComponent(jLabel1)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(jLabel2)
	                .addGap(7, 7, 7)
	                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(18, 18, 18)
	                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addContainerGap(225, Short.MAX_VALUE))
	        );

	        jTabbedPane1.addTab("Вхід", jPanel1);

	        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
	        jLabel3.setText("Рік");
	        jLabel3.setToolTipText("");

	        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
	        jLabel4.setText("К-ст продукції (т)");

	        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
	        jLabel5.setText("Вартість ($)");

	        insertYear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

	        insertProd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

	        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
	        jButton2.setText("Додати");
	        jButton2.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton2ActionPerformed(evt);
	            }
	        });

	        insertCost.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

	        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
	        jPanel2.setLayout(jPanel2Layout);
	        jPanel2Layout.setHorizontalGroup(
	            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel2Layout.createSequentialGroup()
	                .addGap(105, 105, 105)
	                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                    .addGroup(jPanel2Layout.createSequentialGroup()
	                        .addComponent(insertYear, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(74, 74, 74)
	                        .addComponent(insertProd, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(83, 83, 83))
	                    .addGroup(jPanel2Layout.createSequentialGroup()
	                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(83, 83, 83)
	                        .addComponent(jLabel4)
	                        .addGap(75, 75, 75)))
	                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addComponent(insertCost, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addGroup(jPanel2Layout.createSequentialGroup()
	                        .addGap(13, 13, 13)
	                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
	                .addContainerGap(82, Short.MAX_VALUE))
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(309, 309, 309))
	        );
	        jPanel2Layout.setVerticalGroup(
	            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel2Layout.createSequentialGroup()
	                .addGap(124, 124, 124)
	                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addGap(8, 8, 8)
	                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(insertYear, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(insertProd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(insertCost, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addGap(42, 42, 42)
	                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addContainerGap(217, Short.MAX_VALUE))
	        );

	        jTabbedPane1.addTab("Додати", jPanel2);

	        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
	        jLabel9.setText("Введіть рік щоб видалити цей запис");
	        jLabel9.setToolTipText("");

	        delYear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

	        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
	        jButton4.setText("Видалити");
	        jButton4.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton4ActionPerformed(evt);
	            }
	        });

	        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
	        jPanel3.setLayout(jPanel3Layout);
	        jPanel3Layout.setHorizontalGroup(
	            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel3Layout.createSequentialGroup()
	                .addGap(303, 303, 303)
	                .addComponent(delYear, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
	                .addContainerGap(218, Short.MAX_VALUE)
	                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
	                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(201, 201, 201))
	                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
	                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(315, 315, 315))))
	        );
	        jPanel3Layout.setVerticalGroup(
	            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel3Layout.createSequentialGroup()
	                .addGap(126, 126, 126)
	                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(delYear, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(18, 18, 18)
	                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addContainerGap(243, Short.MAX_VALUE))
	        );

	        jTabbedPane1.addTab("Видалити", jPanel3);

	        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
	        jLabel6.setText("Рік");
	        jLabel6.setToolTipText("");

	        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
	        jLabel7.setText("К-ст продукції (т)");

	        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
	        jLabel8.setText("Вартість ($)");

	        updYear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

	        updProd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

	        updCost.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

	        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
	        jButton3.setText("Змінити");
	        jButton3.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton3ActionPerformed(evt);
	            }
	        });

	        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
	        jPanel4.setLayout(jPanel4Layout);
	        jPanel4Layout.setHorizontalGroup(
	            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel4Layout.createSequentialGroup()
	                .addGap(105, 105, 105)
	                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                    .addGroup(jPanel4Layout.createSequentialGroup()
	                        .addComponent(updYear, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(74, 74, 74)
	                        .addComponent(updProd, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(83, 83, 83))
	                    .addGroup(jPanel4Layout.createSequentialGroup()
	                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(83, 83, 83)
	                        .addComponent(jLabel7)
	                        .addGap(75, 75, 75)))
	                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addComponent(updCost, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addGroup(jPanel4Layout.createSequentialGroup()
	                        .addGap(13, 13, 13)
	                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
	                .addContainerGap(82, Short.MAX_VALUE))
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(309, 309, 309))
	        );
	        jPanel4Layout.setVerticalGroup(
	            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel4Layout.createSequentialGroup()
	                .addGap(124, 124, 124)
	                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addGap(8, 8, 8)
	                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(updYear, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(updProd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(updCost, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addGap(42, 42, 42)
	                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addContainerGap(217, Short.MAX_VALUE))
	        );

	        jTabbedPane1.addTab("Редагувати", jPanel4);

	        jTable1.setModel(new javax.swing.table.DefaultTableModel(
	            new Object [][] {

	            },
	            new String [] {

	            }
	        ));
	        jScrollPane1.setViewportView(jTable1);

	        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
	        jButton5.setText("Обновити");
	        jButton5.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton5ActionPerformed(evt);
	            }
	        });

	        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
	        jPanel5.setLayout(jPanel5Layout);
	        jPanel5Layout.setHorizontalGroup(
	            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel5Layout.createSequentialGroup()
	                .addGap(30, 30, 30)
	                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addContainerGap(35, Short.MAX_VALUE))
	        );
	        jPanel5Layout.setVerticalGroup(
	            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
	                .addContainerGap()
	                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(18, 18, 18)
	                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addContainerGap(28, Short.MAX_VALUE))
	        );

	        jTabbedPane1.addTab("Показати", jPanel5);

	        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
	        jButton6.setText("Обновити");
	        jButton6.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton6ActionPerformed(evt);
	            }
	        });

	        jTable2.setModel(new javax.swing.table.DefaultTableModel(
	            new Object [][] {

	            },
	            new String [] {

	            }
	        ));
	        jScrollPane2.setViewportView(jTable2);

	        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

	        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
	        jPanel6.setLayout(jPanel6Layout);
	        jPanel6Layout.setHorizontalGroup(
	            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel6Layout.createSequentialGroup()
	                .addGap(33, 33, 33)
	                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                    .addGroup(jPanel6Layout.createSequentialGroup()
	                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(49, 49, 49)
	                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))
	                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addContainerGap(31, Short.MAX_VALUE))
	        );
	        jPanel6Layout.setVerticalGroup(
	            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel6Layout.createSequentialGroup()
	                .addContainerGap()
	                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
	                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addContainerGap(35, Short.MAX_VALUE))
	        );

	        jTabbedPane1.addTab("Вибірка і розрахунок", jPanel6);

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                .addComponent(jTabbedPane1)
	                .addContainerGap())
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(jTabbedPane1)
	        );

	        pack();
	    }// </editor-fold>                        

	    //actionButton
	    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
	        try {
	            out.writeObject("login");
	            user=jTextField1.getText();
	            pass=jPasswordField1.getPassword();
		out.writeObject(user);
		out.writeObject(new String(pass));
		Object check=in.readObject();
		if (check.equals("suc")) {
	        jTabbedPane1.setEnabledAt(1, true);
	        jTabbedPane1.setEnabledAt(2, true);
	        jTabbedPane1.setEnabledAt(3, true);
	        jTabbedPane1.setEnabledAt(4, true);
	        jTabbedPane1.setEnabledAt(5, true);
	        jTabbedPane1.remove(0);
		}
		 else {
		JOptionPane.showMessageDialog(null, "Невірно введені дані", "Помилка", JOptionPane.ERROR_MESSAGE);
		}
		}catch(IOException | ClassNotFoundException e) {
		   e.printStackTrace();
		   JOptionPane.showMessageDialog(null, "Невірно введені дані", "Помилка", JOptionPane.ERROR_MESSAGE);
		   }       
	    }                                        

	    //select
	    
	    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
	        try {
	            String[] col={"Рік","Виробництво","Вартість"};
	            DefaultTableModel tableModel = (DefaultTableModel)jTable1.getModel();
	            tableModel.setColumnIdentifiers(col);
	            tableModel.setRowCount(0);
	            out.writeObject("select");
	            int len=(Integer)in.readObject();
	            Sunflower[] res=new Sunflower[len];
	            for(int i=0;i<res.length;i++){
	                res[i]=(Sunflower)in.readObject();
	            }
	            for(int i=0;i<len;i++){
	                Object[] temp={res[i].getYear(),res[i].getProduction(),res[i].getCost()};
	                tableModel.addRow(temp);
	            }
	        } catch (IOException | ClassNotFoundException e) { 
			e.printStackTrace();
						}
	    }                                        

	    //insert
	    
	    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
	        int year=Integer.parseInt(insertYear.getText());
	        double prod = Double.parseDouble(insertProd.getText());
	        double cost = Double.parseDouble(insertCost.getText());
	        Sunflower rep = new Sunflower(year,prod,cost);
	        try {
	            out.writeObject("insert");
	            out.writeObject(rep);
	            Object check=in.readObject();
		if (check.equals("suc")) {
	             JOptionPane.showMessageDialog(null, "Успішно додано", "Успіх", JOptionPane.INFORMATION_MESSAGE);
	        }
	        else{
	            JOptionPane.showMessageDialog(null, "Помилка додавання", "Помилка", JOptionPane.ERROR_MESSAGE);
	        }
	        } catch (IOException | ClassNotFoundException ex) {
	            ex.printStackTrace();
	        }
	    }                                        

	    //update
	    
	    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
	        int year=Integer.parseInt(updYear.getText());
	        double prod = Double.parseDouble(updProd.getText());
	        double cost = Double.parseDouble(updCost.getText());
	        Sunflower rep = new Sunflower(year,prod,cost);
	        try {
	            out.writeObject("update");
	            out.writeObject(rep);
	            Object check=in.readObject();
		if (check.equals("suc")) {
	             JOptionPane.showMessageDialog(null, "Успішно оновлено", "Успіх", JOptionPane.INFORMATION_MESSAGE);
	        }
	        else{
	            JOptionPane.showMessageDialog(null, "Помилка оновлення", "Помилка", JOptionPane.ERROR_MESSAGE);
	        }
	        } catch (IOException | ClassNotFoundException ex) {
	            ex.printStackTrace();
	        }
	    }                                        

	//delete
	    
	    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
	        int year=Integer.parseInt(delYear.getText());
	         try {
	            out.writeObject("delete");
	            out.writeObject(year);
	            Object check=in.readObject();
		if (check.equals("suc")) {
	             JOptionPane.showMessageDialog(null, "Успішно видалено", "Успіх", JOptionPane.INFORMATION_MESSAGE);
	        }
	        else{
	            JOptionPane.showMessageDialog(null, "Помилка видалення", "Помилка", JOptionPane.ERROR_MESSAGE);
	        }
	        } catch (IOException | ClassNotFoundException ex) {
	            ex.printStackTrace();
	        }
	    }                                        

	    //show sample
	    
	    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
	        try {
	            String[] col={"Рік","Виробництво","Вартість"};
	            DefaultTableModel tableModel = (DefaultTableModel)jTable2.getModel();
	            tableModel.setColumnIdentifiers(col);
	            tableModel.setRowCount(0);
	            out.writeObject("showsamp");
	            double avg=(Double)in.readObject();
	            int len=(Integer)in.readObject();
	            Sunflower[] res=new Sunflower[len];
	            for(int i=0;i<res.length;i++){
	                res[i]=(Sunflower)in.readObject();
	            }
	            for(int i=0;i<len;i++){
	                Object[] temp={res[i].getYear(),res[i].getProduction(),res[i].getCost()};
	                tableModel.addRow(temp);
	            }
	            jLabel10.setText("Серндньорiчне виробництво : "+new DecimalFormat("#0.000").format(avg));
	        } catch (IOException | ClassNotFoundException e) { 
			e.printStackTrace();
	        }
	    }                                        


	    // Variables declaration - do not modify                     
	    private javax.swing.JTextField delYear;
	    private javax.swing.JTextField insertCost;
	    private javax.swing.JTextField insertProd;
	    private javax.swing.JTextField insertYear;
	    private javax.swing.JButton jButton1;
	    private javax.swing.JButton jButton2;
	    private javax.swing.JButton jButton3;
	    private javax.swing.JButton jButton4;
	    private javax.swing.JButton jButton5;
	    private javax.swing.JButton jButton6;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel10;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel jLabel3;
	    private javax.swing.JLabel jLabel4;
	    private javax.swing.JLabel jLabel5;
	    private javax.swing.JLabel jLabel6;
	    private javax.swing.JLabel jLabel7;
	    private javax.swing.JLabel jLabel8;
	    private javax.swing.JLabel jLabel9;
	    private javax.swing.JPanel jPanel1;
	    private javax.swing.JPanel jPanel2;
	    private javax.swing.JPanel jPanel3;
	    private javax.swing.JPanel jPanel4;
	    private javax.swing.JPanel jPanel5;
	    private javax.swing.JPanel jPanel6;
	    private javax.swing.JPasswordField jPasswordField1;
	    private javax.swing.JScrollPane jScrollPane1;
	    private javax.swing.JScrollPane jScrollPane2;
	    private javax.swing.JTabbedPane jTabbedPane1;
	    private javax.swing.JTable jTable1;
	    private javax.swing.JTable jTable2;
	    private javax.swing.JTextField jTextField1;
	    private javax.swing.JTextField updCost;
	    private javax.swing.JTextField updProd;
	    private javax.swing.JTextField updYear;
	    // End of variables declaration                   
	}

